# api.py - FastAPI streaming chat server

import uuid
import json
from typing import Optional

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from customer_support_chat.app.graph import multi_agentic_graph
from customer_support_chat.app.services.utils import download_and_prepare_db
from customer_support_chat.app.core.logger import logger

app = FastAPI(title="Customer Support Chat API")

# CORS middleware for frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    message: str
    passenger_id: str = "5102 899977"
    thread_id: Optional[str] = None


@app.on_event("startup")
async def startup():
    download_and_prepare_db()


@app.get("/health")
async def health_check():
    """健康检查端点，用于负载均衡器检测"""
    return {"status": "healthy", "service": "customer-support-chat"}


@app.get("/", response_class=HTMLResponse)
async def index():
    """Serve the chat frontend"""
    with open("customer_support_chat/app/templates/index.html", "r", encoding="utf-8") as f:
        return f.read()


@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    """
    Streaming chat endpoint using Server-Sent Events (SSE).
    Returns a stream of messages as they are generated by the LLM.
    """
    thread_id = request.thread_id or str(uuid.uuid4())

    config = {
        "configurable": {
            "passenger_id": request.passenger_id,
            "thread_id": thread_id,
        }
    }

    async def event_generator():
        # Track printed message IDs to avoid duplicates
        printed_message_ids = set()

        try:
            # 使用 astream 实现真正的异步流式处理
            async for event in multi_agentic_graph.astream(
                {"messages": [("user", request.message)]},
                config,
                stream_mode="values"
            ):
                messages = event.get("messages", [])
                for message in messages:
                    if message.id not in printed_message_ids:
                        message_type = type(message).__name__
                        content = message.content if hasattr(message, "content") else str(message)

                        # Stream the message
                        yield f"event: message\ndata: {json.dumps({
                            "type": message_type,
                            "content": content,
                            "id": message.id
                        }, ensure_ascii=False)}\n\n"

                        printed_message_ids.add(message.id)

            # Check for interrupts (sensitive tools requiring approval)
            snapshot = multi_agentic_graph.get_state(config)
            if snapshot.next:
                yield f"event: interrupt\ndata: {json.dumps({'requires_approval': True})}\n\n"

            yield f"event: done\ndata: {json.dumps({'thread_id': thread_id})}\n\n"

        except Exception as e:
            logger.error(f"Stream error: {e}")
            yield f"event: error\ndata: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        }
    )


@app.post("/chat/approve")
async def approve_action(request: Request):
    """
    Approve a sensitive action (e.g., booking).
    Continues the graph execution after user approval.
    """
    body = await request.json()
    thread_id = body.get("thread_id")
    approved = body.get("approved", True)
    feedback = body.get("feedback", "")

    config = {
        "configurable": {
            "thread_id": thread_id,
        }
    }

    try:
        snapshot = multi_agentic_graph.get_state(config)

        if not snapshot.next:
            return {"status": "no_pending_action"}

        if approved:
            result = await multi_agentic_graph.ainvoke(None, config)
        else:
            # User denied the action
            tool_call_id = snapshot.value["messages"][-1].tool_calls[0]["id"]
            from langchain_core.messages import ToolMessage
            result = await multi_agentic_graph.ainvoke(
                {
                    "messages": [
                        ToolMessage(
                            tool_call_id=tool_call_id,
                            content=f"API call denied by user. Reasoning: '{feedback}'. Continue assisting, accounting for the user's input.",
                        )
                    ]
                },
                config,
            )

        messages = result.get("messages", [])
        return {
            "status": "approved" if approved else "denied",
            "messages": [
                {
                    "type": type(m).__name__,
                    "content": m.content if hasattr(m, "content") else str(m),
                }
                for m in messages[-5:]  # Return last 5 messages
            ]
        }

    except Exception as e:
        logger.error(f"Approval error: {e}")
        return {"status": "error", "error": str(e)}


@app.get("/chat/history/{thread_id}")
async def get_history(thread_id: str):
    """Retrieve conversation history for a thread"""
    config = {
        "configurable": {
            "thread_id": thread_id,
        }
    }

    try:
        snapshot = multi_agentic_graph.get_state(config)
        messages = snapshot.values.get("messages", [])
        return {
            "messages": [
                {
                    "type": type(m).__name__,
                    "content": m.content if hasattr(m, "content") else str(m),
                }
                for m in messages
            ]
        }
    except Exception as e:
        return {"messages": [], "error": str(e)}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
